<a href="https://colab.research.google.com/github/haokeliu/colaboratory/blob/master/pytorch%E5%AD%A6%E4%B9%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("hello word")

hello word


In [0]:
!pip3 install torch

In [0]:
import numpy as np
import torch

In [0]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
print("Size:()".format(x.shape))
print("Valuses:\n{}".format(x))

Type:torch.FloatTensor
Size:()
Valuses:
tensor([[4.6520e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 1.5554e-43, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [0]:
x = torch.randn(2,3)
print(x)

tensor([[0.7386, 0.1633, 1.2330],
        [0.5824, 0.8477, 1.6136]])


In [0]:
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [0]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
x = x.long()
print("Type:{}".format(x.type()))

Type:torch.FloatTensor
Type:torch.LongTensor


In [0]:
x = torch.randn(2,3)

In [0]:
y =torch.randn(2,3)
z = x+y

In [0]:
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 3])
values:
tensor([[-1.3409, -2.0613, -2.0996],
        [ 0.6537, -0.4032, -1.4478]])


In [0]:
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 2])
values:
tensor([[ 0.1994,  2.2825],
        [-0.1956, -0.6065]])


In [0]:
x = torch.randn(2,3)
print("size:{}".format(x.shape))
print('values:\n{}'.format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

size:torch.Size([2, 3])
values:
tensor([[-0.6660, -0.2810,  1.4448],
        [ 1.5700, -0.2242,  0.1157]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.6660,  1.5700],
        [-0.2810, -0.2242],
        [ 1.4448,  0.1157]])


In [0]:
z = x.view(3,2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.6660, -0.2810],
        [ 1.4448,  1.5700],
        [-0.2242,  0.1157]])
