<a href="https://colab.research.google.com/github/haokeliu/colaboratory/blob/master/pytorch%E5%AD%A6%E4%B9%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello word")

hello word


**Tensor 基础知识**


---


In [3]:
!pip3 install torch

In [0]:
import numpy as np
import torch

In [5]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
print("Size:()".format(x.shape))
print("Valuses:\n{}".format(x))

Type:torch.FloatTensor
Size:()
Valuses:
tensor([[4.4008e-37, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 1.6723e-24, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [6]:
x = torch.randn(2,3)
print(x)

tensor([[ 1.0009, -0.6725,  0.3778],
        [ 1.6308,  1.3183, -0.6085]])


In [7]:
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
x = x.long()
print("Type:{}".format(x.type()))

Type:torch.FloatTensor
Type:torch.LongTensor


 **Tensor 运算**





---








In [0]:
x = torch.randn(2,3)

In [0]:
y =torch.randn(2,3)
z = x+y

In [11]:
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 3])
values:
tensor([[ 0.3613, -0.0955, -2.2046],
        [-0.0296,  0.3024, -0.5606]])


In [12]:
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 2])
values:
tensor([[-2.8218, -1.7758],
        [ 0.8664, -0.7353]])


In [13]:
x = torch.randn(2,3)
print("size:{}".format(x.shape))
print('values:\n{}'.format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

size:torch.Size([2, 3])
values:
tensor([[ 0.4594, -0.8403,  1.7724],
        [-0.4043, -1.4127,  0.5877]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.4594, -0.4043],
        [-0.8403, -1.4127],
        [ 1.7724,  0.5877]])


In [14]:
z = x.view(3,2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.4594, -0.8403],
        [ 1.7724, -0.4043],
        [-1.4127,  0.5877]])


In [15]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("x.size = ",x.size(1))
print('size:{}'.format(x.shape))
print("valuse: \n{}\n".format(x))
a = x.view(x.size(1),-1)
print('size:{}'.format(a.shape))
print("valuse: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

x.size =  3
size:torch.Size([2, 3, 4])
valuse: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

size:torch.Size([3, 8])
valuse: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [16]:
x = torch.randn(2,3)
print("values:\n{}".format(x))
y = torch.sum(x,dim=0) # 为每列添加各行叠加的值
print("values: \n{}".format(y))
z = torch.sum(x,dim=1)# 为每行添加各列叠加的值
print("values:\n{}".format(z))

values:
tensor([[-1.4294,  0.7661,  0.8125],
        [ 0.2685, -0.2799,  0.8751]])
values: 
tensor([-1.1608,  0.4862,  1.6876])
values:
tensor([0.1491, 0.8638])


**索引，切片和级联**


---



In [17]:
x = torch.randn(3,4)
print("x:\n{}".format(x))
print("x[:1]:\n{}".format(x[:1]))
print("x[:1,1:3]\n{}".format(x[:1,1:3]))

x:
tensor([[ 0.9025,  3.1423, -1.8739,  0.3658],
        [ 0.2474, -0.6374, -1.0558, -1.9290],
        [ 0.5500,  0.6942, -0.3295,  0.1366]])
x[:1]:
tensor([[ 0.9025,  3.1423, -1.8739,  0.3658]])
x[:1,1:3]
tensor([[ 3.1423, -1.8739]])


In [18]:
# 选择维度索引
x = torch.randn(2,3)
print("vualues:\n{}".format(x))
col_indices = torch.LongTensor([0,2])
print("col_indices:\n{}".format(col_indices))
chosen = torch.index_select(x,dim=1,index =col_indices)# 第0和第2列的值
print("values:\nP{}".format(chosen))
row_indices = torch.LongTensor([0,1])
chosen = x[row_indices,col_indices]# 来自（0,0）和（2,1）的值
print("values:\nP{}".format(chosen))

vualues:
tensor([[ 0.7549, -1.0409, -0.1362],
        [-0.2283, -0.4996,  0.5826]])
col_indices:
tensor([0, 2])
values:
Ptensor([[ 0.7549, -0.1362],
        [-0.2283,  0.5826]])
values:
Ptensor([0.7549, 0.5826])


In [19]:
# 级联
x = torch.randn(2,3)
print("values:\n{}".format(x))
y = torch.cat([x,x],dim=0) # 按行堆叠（dim = 1按列堆叠）
print("values:\n{}".format(y))
y = torch.cat([x,x],dim=1) # 按列堆叠
print("values:\n{}".format(y))
#y = torch.cat([x,x],dim=2) # 按列堆叠（dim = 1按列堆叠）
#IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

values:
tensor([[ 0.2869, -0.1382,  0.9660],
        [-0.6809, -0.3212,  0.5894]])
values:
tensor([[ 0.2869, -0.1382,  0.9660],
        [-0.6809, -0.3212,  0.5894],
        [ 0.2869, -0.1382,  0.9660],
        [-0.6809, -0.3212,  0.5894]])
values:
tensor([[ 0.2869, -0.1382,  0.9660,  0.2869, -0.1382,  0.9660],
        [-0.6809, -0.3212,  0.5894, -0.6809, -0.3212,  0.5894]])


**梯度**


---



In [20]:
# 带有gradient bookkeeping的张量
x = torch.rand(3,4,requires_grad=True)
y = 3*x+2
z = y.mean()
z.backward() # z是标量
print("values:\n{}".format(x))
print("x.grad:\n",x.grad)

values:
tensor([[0.6141, 0.9284, 0.1290, 0.8803],
        [0.8858, 0.0073, 0.2999, 0.7634],
        [0.0055, 0.8587, 0.8479, 0.0309]], requires_grad=True)
x.grad:
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


>y = 3x + 2$

>$z = \sum{y}/N$

> $\frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(z)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25$

>此时N = 12带入上式得出






**CUDA 张量**


---



In [21]:
print(torch.cuda.torch.cuda.is_available())

True


In [22]:
# 创建一个CPU版的0张量
x = torch.Tensor(3,4).to("cpu")
print("Type:{}".format(x.type()))

Type:torch.FloatTensor


In [23]:
x = torch.Tensor(3,4).to("cuda")
print("type:{}".format(x.type()))

type:torch.cuda.FloatTensor
