In [0]:
print("hello word")

hello word


**Tensor 基础知识**


---


In [0]:
!pip3 install torch

In [0]:
import numpy as np
import torch

In [0]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
print("Size:()".format(x.shape))
print("Valuses:\n{}".format(x))

Type:torch.FloatTensor
Size:()
Valuses:
tensor([[4.3639e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [0]:
x = torch.randn(2,3)
print(x)

tensor([[-0.6505, -0.7792, -0.7866],
        [-0.3394, -0.2947,  0.7264]])


In [0]:
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [0]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
x = x.long()
print("Type:{}".format(x.type()))

Type:torch.FloatTensor
Type:torch.LongTensor


 **Tensor 运算**





---








In [0]:
x = torch.randn(2,3)

In [0]:
y =torch.randn(2,3)
z = x+y

In [0]:
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 3])
values:
tensor([[-0.0868,  0.7308,  0.3562],
        [-1.4166, -0.4415, -0.8053]])


In [0]:
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print("size:{}".format(z.shape))
print("values:\n{}".format(z))

size:torch.Size([2, 2])
values:
tensor([[ 1.4935,  1.3308],
        [-2.1882, -1.6207]])


In [0]:
x = torch.randn(2,3)
print("size:{}".format(x.shape))
print('values:\n{}'.format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

size:torch.Size([2, 3])
values:
tensor([[ 1.1473, -0.7543, -1.0998],
        [-1.0498,  0.8755,  0.5418]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 1.1473, -1.0498],
        [-0.7543,  0.8755],
        [-1.0998,  0.5418]])


In [0]:
z = x.view(3,2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 1.1473, -0.7543],
        [-1.0998, -1.0498],
        [ 0.8755,  0.5418]])


In [0]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("x.size = ",x.size(1))
print('size:{}'.format(x.shape))
print("valuse: \n{}\n".format(x))
a = x.view(x.size(1),-1)
print('size:{}'.format(a.shape))
print("valuse: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

x.size =  3
size:torch.Size([2, 3, 4])
valuse: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

size:torch.Size([3, 8])
valuse: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [0]:
x = torch.randn(2,3)
print("values:\n{}".format(x))
y = torch.sum(x,dim=0) # 为每列添加各行叠加的值
print("values: \n{}".format(y))
z = torch.sum(x,dim=1)# 为每行添加各列叠加的值
print("values:\n{}".format(z))

values:
tensor([[-0.7470, -0.0903, -0.5821],
        [ 0.6926,  1.2514,  1.3672]])
values: 
tensor([-0.0544,  1.1611,  0.7851])
values:
tensor([-1.4194,  3.3112])


**索引，切片和级联**


---



In [0]:
x = torch.randn(3,4)
print("x:\n{}".format(x))


x:
tensor([[-0.4745, -1.7565,  1.4486, -1.0095],
        [-1.4893,  0.5599,  1.2234, -0.6488],
        [-0.5833, -1.2775, -0.6946, -1.7526]])
